background {
    color = rgba(0, 0, 0, 1.0)
}

input-field {
    size = 250, 50
    outline_thickness = 3
    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1.0)
    fade_on_empty = false
}
